### PR TITLE
Add noctis-uva theme

### PR DESCRIPTION
**Pull request by ChachyDev**

### CODE REVIEW

**Comment by proudmuslim-dev** [comment]
Imo this looks a bit too similar to dracula, but I'll leave this open as I might merge it later

**Comment by ChachyDev** [comment]
Hm, I'll see if I can make it fit the color scheme more since the file itself is based off dracula

**Comment by proudmuslim-dev** [comment]
Ah alright

**Review by proudmuslim-dev — APPROVED** [review]
LGTM :+1:

**Pull request merged**
